Adding a sample for Flutter Codelab first
Tensegritics/ClojureDart pull request #197
Opened 2023-02-14 06:12 UTC by ianffcs

Adding an example for:

https://codelabs.developers.google.com/codelabs/flutter-codelab-first

2023-02-15 13:03 UTC, cgrand reviewed
I haven't run it yet but my comments are mostly nitpicking. Good job!

2023-02-15 13:03 UTC, cgrand commented on samples/first_flutter_app_codelabs/first_flutter_app_codelabs.cljd
> +    (fn [_ constraints]
`(f/builld [constraints]` works too

2023-02-16 08:50 UTC, dupuchba requested changes
appart from the little comment, all is good

2023-02-16 08:50 UTC, dupuchba commented on samples/first_flutter_app_codelabs/README.md
> +clj -M:cljd init
it's the other way around, 1st init then flutter pub add en...

2023-02-16 16:30 UTC, dupuchba approved these changes
Thanks a lot

2023-02-16 16:31 UTC, merged